
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dede S
 */
public class Latihan extends javax.swing.JFrame {

    /**
     * Creates new form Latihan
     */
    public Latihan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1_dedesaepulloh = new javax.swing.JLabel();
        jLabel2_dedesaepulloh = new javax.swing.JLabel();
        jButton1_dedesaepulloh = new javax.swing.JButton();
        jButton2_dedesaepulloh = new javax.swing.JButton();
        jButton3_dedesaepulloh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1_dedesaepulloh.setText("jLabel1");

        jLabel2_dedesaepulloh.setText("jLabel1");

        jButton1_dedesaepulloh.setText("TAMPILKAN");
        jButton1_dedesaepulloh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1_dedesaepullohMouseClicked(evt);
            }
        });

        jButton2_dedesaepulloh.setText("PUTAR");
        jButton2_dedesaepulloh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2_dedesaepullohActionPerformed(evt);
            }
        });

        jButton3_dedesaepulloh.setText("KELUAR");
        jButton3_dedesaepulloh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_dedesaepullohActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2_dedesaepulloh)
                            .addComponent(jLabel1_dedesaepulloh))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1_dedesaepulloh)
                        .addGap(41, 41, 41)
                        .addComponent(jButton2_dedesaepulloh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(jButton3_dedesaepulloh)
                        .addGap(31, 31, 31))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1_dedesaepulloh)
                .addGap(26, 26, 26)
                .addComponent(jLabel2_dedesaepulloh)
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1_dedesaepulloh)
                    .addComponent(jButton2_dedesaepulloh)
                    .addComponent(jButton3_dedesaepulloh))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1_dedesaepullohMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1_dedesaepullohMouseClicked
        // TODO add your handling code here:
        jLabel1_dedesaepulloh.setText("Selamat Datang");
        jLabel2_dedesaepulloh.setText("Pemrograman 7");
        jLabel1_dedesaepulloh.setForeground(Color.red);
        jLabel2_dedesaepulloh.setForeground(Color.red);
    }//GEN-LAST:event_jButton1_dedesaepullohMouseClicked

    private void jButton2_dedesaepullohActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2_dedesaepullohActionPerformed
        // TODO add your handling code here:
        jLabel2_dedesaepulloh.setText("Selamat Datang");
        jLabel1_dedesaepulloh.setText("Pemrograman 7");
        jLabel1_dedesaepulloh.setForeground(Color.blue);
        jLabel2_dedesaepulloh.setForeground(Color.blue);
    }//GEN-LAST:event_jButton2_dedesaepullohActionPerformed

    private void jButton3_dedesaepullohActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_dedesaepullohActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton3_dedesaepullohActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_dedesaepulloh;
    private javax.swing.JButton jButton2_dedesaepulloh;
    private javax.swing.JButton jButton3_dedesaepulloh;
    private javax.swing.JLabel jLabel1_dedesaepulloh;
    private javax.swing.JLabel jLabel2_dedesaepulloh;
    // End of variables declaration//GEN-END:variables
}
